### ISSUE TITLE
Unable to delete member

### ISSUE THREAD

**Issue by MichaelLok** [jeng6529/Bus-Ticketing-System#1]
The system still unable delete member

**Comment by jeng6529** [comment]
so we should do a function for staff to delete member details?

**Comment by taiyungtan96** [comment]
i dont think we have to delete the member's details. 
instead of delete the member details. why dont we just classify it into another category which is not active?

**Comment by chongyimiao** [comment]
I think that a good idea for change the member's status from "Active" to "Not Active" compare to direct delete the member details.

**Comment by MichaelLok** [comment]
Its good idea, but delete member may be some useful tools for permanently delete user. For example, some unauthorized user, spam user and other. So I think add-on this function can help to arrange member database.

**Comment by jeng6529** [comment]
Yes you are right, the member will be change to inactive when the expired date has pass, member can renew his/her member expired date by paying membership fees, and the member that is inactivate more than 1 year then will perform a delete member

**Comment by MichaelLok** [comment]
I agree with you point, how about other?

**Comment by shaomingli96** [comment]
I think we should have the search member details while processing member deletion, this may help the user to search specific target to delete the user details more quickly and won't delete other member details

**Comment by MichaelLok** [comment]
Okay, so i will start the delete member function coding now
